
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import oracle.sql.BLOB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saurabh Mishra
 */
public class Update_Details extends javax.swing.JFrame {

    /**
     * Creates new form Update_Details
     */
    public Update_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name7 = new javax.swing.JLabel();
        updatestudentname = new javax.swing.JTextField();
        name4 = new javax.swing.JLabel();
        updaterollno = new javax.swing.JTextField();
        name2 = new javax.swing.JLabel();
        updatebranch = new javax.swing.JTextField();
        name3 = new javax.swing.JLabel();
        updateroomno = new javax.swing.JTextField();
        name1 = new javax.swing.JLabel();
        updatedate = new org.jdesktop.swingx.JXDatePicker();
        name = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        name5 = new javax.swing.JLabel();
        updateaddress = new javax.swing.JTextField();
        name6 = new javax.swing.JLabel();
        choosefile = new javax.swing.JButton();
        updatephotopath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewtable = new javax.swing.JTable();
        viewlist = new javax.swing.JButton();
        clearall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        name7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name7.setText("Name :");

        updatestudentname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updatestudentname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatestudentnameActionPerformed(evt);
            }
        });

        name4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name4.setText("Roll No :");

        updaterollno.setEditable(false);
        updaterollno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updaterollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updaterollnoActionPerformed(evt);
            }
        });

        name2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name2.setText("Branch :");

        updatebranch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updatebranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebranchActionPerformed(evt);
            }
        });

        name3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name3.setText("Room No :");

        updateroomno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateroomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateroomnoActionPerformed(evt);
            }
        });

        name1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1.setText("Date of Birth :");

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText("Gender :");

        gender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        name5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name5.setText("Full Address :");

        updateaddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateaddressActionPerformed(evt);
            }
        });

        name6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name6.setText("Add Photo :");

        choosefile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        choosefile.setText("Choose File");
        choosefile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choosefileMouseClicked(evt);
            }
        });
        choosefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosefileActionPerformed(evt);
            }
        });

        updatephotopath.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updatephotopath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatephotopathActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Update Student Details");

        jButton1.setBackground(new java.awt.Color(102, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(240, 60, 60));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        viewtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ROLLNUMBER", "NAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewtable.getTableHeader().setReorderingAllowed(false);
        viewtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewtable);

        viewlist.setBackground(new java.awt.Color(85, 187, 85));
        viewlist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewlist.setForeground(new java.awt.Color(148, 117, 110));
        viewlist.setText("View Student List");
        viewlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlistActionPerformed(evt);
            }
        });

        clearall.setBackground(new java.awt.Color(102, 102, 102));
        clearall.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearall.setForeground(new java.awt.Color(255, 255, 255));
        clearall.setText("Clear");
        clearall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearallMouseClicked(evt);
            }
        });
        clearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewlist)
                        .addGap(24, 24, 24)
                        .addComponent(clearall, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name1)
                                    .addComponent(name5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updatedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updaterollno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(choosefile)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(updatephotopath, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(updatestudentname, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updatebranch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateroomno, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatestudentname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updaterollno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updatebranch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name2))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateroomno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updatedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choosefile)
                            .addComponent(updatephotopath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewlist, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearall, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatestudentnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatestudentnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatestudentnameActionPerformed

    private void updaterollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updaterollnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updaterollnoActionPerformed

    private void updatebranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebranchActionPerformed

    private void updateroomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateroomnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateroomnoActionPerformed

    private void updateaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateaddressActionPerformed

    private void choosefileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choosefileMouseClicked
        new filechooser().setVisible(true);
    }//GEN-LAST:event_choosefileMouseClicked

    private void choosefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosefileActionPerformed
        String n1 = updatestudentname.getText();
        JFileChooser chooser1 = new JFileChooser();
        chooser1.showOpenDialog(null);
        File f = chooser1.getSelectedFile();
        String filename = f.getAbsolutePath();
        updatephotopath.setText(filename);
        

    }//GEN-LAST:event_choosefileActionPerformed

    private void updatephotopathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatephotopathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatephotopathActionPerformed

    private void viewtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewtableMouseClicked
      String data = null;
            if(viewtable.getSelectedRow()!=-1 && viewtable.getSelectedColumn()!=-1)
             {
              data = viewtable.getValueAt(viewtable.getSelectedRow(),viewtable.getSelectedColumn()).toString();
              Connection con =null;
              PreparedStatement pst;
              ResultSet rs;
             
              String roll=null , name=null , dob =null ,br=null, add=null ,sex=null;
              int room = 0;
              BLOB pic = null;
              BufferedInputStream pics = null;
              
            
           
          try  {
                 Class.forName("oracle.jdbc.OracleDriver");
                 con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","saurabh","mca713209");
                 
                 pst = con.prepareStatement("select * from students where rollno='"+data+"'");
                
                 rs = pst.executeQuery();
              
                 while(rs.next())
                  {
                   roll = rs.getString("rollno");
                   name = rs.getString("sname");
                     br = rs.getString("branch");
                    sex = rs.getString("gender");
                    add = rs.getString("address");
                   room = rs.getInt("roomnumber");
                    dob = rs.getString("birthdate");
                    pic = (BLOB)rs.getBlob("photograph");
                  }
                 pics=new BufferedInputStream(pic.getBinaryStream());
                 Image raw = ImageIO.read(pics);
                 
                 updatestudentname.setText(name);
                  updaterollno.setText(roll);
                   updatebranch.setText(br);
                      gender.setText(sex);
                     updateaddress.setText(add);
                      updateroomno.setText(Integer.toString(room));
                      
                     // updatephotopath.setText(pic);
                     
                    DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
                        Date dob1 = df.parse(dob);
                       updatedate.setDate(dob1);
                
                 
          
                } 
       catch(ClassNotFoundException ex)
                {
                  Logger.getLogger(viewstudent.class.getName()).log(Level.SEVERE, null, ex);
                } 
       catch(SQLException ex)
                {
                 Logger.getLogger(viewstudent.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) { 
            Logger.getLogger(viewstudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
              Logger.getLogger(Update_Details.class.getName()).log(Level.SEVERE, null, ex);
          }
        try {
            con.close();
        } 
        catch (SQLException ex) {
            Logger.getLogger(viewstudent.class.getName()).log(Level.SEVERE, null, ex);
        }  
     }

    }//GEN-LAST:event_viewtableMouseClicked

    private void viewlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlistActionPerformed
        DefaultTableModel model = (DefaultTableModel)viewtable.getModel();
        Connection con = null;
        PreparedStatement pst=null;
        ResultSet rs;
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","saurabh","mca713209");
            pst = con.prepareStatement("select rollno,sname from students");
            rs=pst.executeQuery();
            while(rs.next())
            {
                String roll = rs.getString("rollno");
                String name = rs.getString("sname");

                model.addRow(new Object[] {roll ,name});
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(viewstudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(viewstudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewlistActionPerformed

    private void clearallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearallMouseClicked
        
        DefaultTableModel model = (DefaultTableModel)viewtable.getModel();
        while(model.getRowCount()>0)
        {
            for(int i=0;i<model.getRowCount();i++)
            {
                model.removeRow(i);
            }
        }
    }//GEN-LAST:event_clearallMouseClicked

    private void clearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearallActionPerformed
        updatestudentname.setText(null);
        updaterollno.setText(null);
        updatebranch.setText(null);
        updateroomno.setText(null);
        updatedate.setDate(null);
        gender.setText(null);
        updateaddress.setText(null);
        updatephotopath.setText(null);
    }//GEN-LAST:event_clearallActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        setVisible(false);
        new viewstudent().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String data=null;
        if(viewtable.getSelectedRow()!=-1 && viewtable.getSelectedColumn()!=-1)
       {
         data = viewtable.getValueAt(viewtable.getSelectedRow(),viewtable.getSelectedColumn()).toString();
        Connection con = null; 
          String n = updatestudentname.getText();
       String roll = updaterollno.getText();
         String br = updatebranch.getText();
        String gen = gender.getText();
        String add = updateaddress.getText();
          int room = Integer.parseInt(updateroomno.getText());
          
         Date oDate = updatedate.getDate();
     DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
          String d = df.format(oDate);
     // BLOB newpic  = null;
  String updatepic = updatephotopath.getText();
    
      
         
          
      PreparedStatement pst=null;
        try {
              Class.forName("oracle.jdbc.OracleDriver");
              con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","saurabh","mca713209");
             
              pst = con.prepareStatement("update students set sname='"+n+"',branch='"+br+"',gender='"+gen+"',address='"+add+"',roomnumber='"+room+"',birthdate='"+d+"',photograph=? where rollno='"+data+"'");
              FileInputStream fine = new FileInputStream(updatepic); 
              pst.setBinaryStream(1,fine,fine.available());
              int i=pst.executeUpdate();
              con.close();
            }
        catch (SQLException ex)
               {
                ex.printStackTrace();
               } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(student_datails.class.getName()).log(Level.SEVERE, null, ex);
        } 
       catch (FileNotFoundException ex) {
            Logger.getLogger(student_datails.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (IOException ex) {
            Logger.getLogger(student_datails.class.getName()).log(Level.SEVERE, null, ex);
        }
        showMessageDialog(null,"Record has been updated successfully");
       } 
     else
         showMessageDialog(null,"Please select a row.");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choosefile;
    private javax.swing.JButton clearall;
    private javax.swing.JTextField gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JTextField updateaddress;
    private javax.swing.JTextField updatebranch;
    private org.jdesktop.swingx.JXDatePicker updatedate;
    private javax.swing.JTextField updatephotopath;
    private javax.swing.JTextField updaterollno;
    private javax.swing.JTextField updateroomno;
    private javax.swing.JTextField updatestudentname;
    private javax.swing.JButton viewlist;
    private javax.swing.JTable viewtable;
    // End of variables declaration//GEN-END:variables
}
